// Generated by gencpp from file nubot_pummba_msg/PummbaCmd.msg
// DO NOT EDIT!


#ifndef NUBOT_PUMMBA_MSG_MESSAGE_PUMMBACMD_H
#define NUBOT_PUMMBA_MSG_MESSAGE_PUMMBACMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nubot_pummba_msg
{
template <class ContainerAllocator>
struct PummbaCmd_
{
  typedef PummbaCmd_<ContainerAllocator> Type;

  PummbaCmd_()
    : vel_linear(0.0)
    , vel_angular(0.0)
    , front_left(0.0)
    , front_right(0.0)
    , rear_left(0.0)
    , rear_right(0.0)  {
    }
  PummbaCmd_(const ContainerAllocator& _alloc)
    : vel_linear(0.0)
    , vel_angular(0.0)
    , front_left(0.0)
    , front_right(0.0)
    , rear_left(0.0)
    , rear_right(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_linear_type;
  _vel_linear_type vel_linear;

   typedef float _vel_angular_type;
  _vel_angular_type vel_angular;

   typedef float _front_left_type;
  _front_left_type front_left;

   typedef float _front_right_type;
  _front_right_type front_right;

   typedef float _rear_left_type;
  _rear_left_type rear_left;

   typedef float _rear_right_type;
  _rear_right_type rear_right;





  typedef boost::shared_ptr< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PummbaCmd_

typedef ::nubot_pummba_msg::PummbaCmd_<std::allocator<void> > PummbaCmd;

typedef boost::shared_ptr< ::nubot_pummba_msg::PummbaCmd > PummbaCmdPtr;
typedef boost::shared_ptr< ::nubot_pummba_msg::PummbaCmd const> PummbaCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator1> & lhs, const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator2> & rhs)
{
  return lhs.vel_linear == rhs.vel_linear &&
    lhs.vel_angular == rhs.vel_angular &&
    lhs.front_left == rhs.front_left &&
    lhs.front_right == rhs.front_right &&
    lhs.rear_left == rhs.rear_left &&
    lhs.rear_right == rhs.rear_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator1> & lhs, const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nubot_pummba_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37f5dcb42b8ba6407dc6ea2389a5de4c";
  }

  static const char* value(const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37f5dcb42b8ba640ULL;
  static const uint64_t static_value2 = 0x7dc6ea2389a5de4cULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_pummba_msg/PummbaCmd";
  }

  static const char* value(const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel_linear\n"
"float32 vel_angular\n"
"float32 front_left\n"
"float32 front_right\n"
"float32 rear_left\n"
"float32 rear_right\n"
;
  }

  static const char* value(const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_linear);
      stream.next(m.vel_angular);
      stream.next(m.front_left);
      stream.next(m.front_right);
      stream.next(m.rear_left);
      stream.next(m.rear_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PummbaCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_pummba_msg::PummbaCmd_<ContainerAllocator>& v)
  {
    s << indent << "vel_linear: ";
    Printer<float>::stream(s, indent + "  ", v.vel_linear);
    s << indent << "vel_angular: ";
    Printer<float>::stream(s, indent + "  ", v.vel_angular);
    s << indent << "front_left: ";
    Printer<float>::stream(s, indent + "  ", v.front_left);
    s << indent << "front_right: ";
    Printer<float>::stream(s, indent + "  ", v.front_right);
    s << indent << "rear_left: ";
    Printer<float>::stream(s, indent + "  ", v.rear_left);
    s << indent << "rear_right: ";
    Printer<float>::stream(s, indent + "  ", v.rear_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_PUMMBA_MSG_MESSAGE_PUMMBACMD_H
